### ISSUE TITLE
Manager UI improvements

### ISSUE THREAD

**Issue by Xuerian** [Vswe/ModJam3#17]
- Panning of work area, currently have to break up into multiple managers
- Break all lists into vertical, scrollable rows instead of horizontal lists
- Support mousewheel in lists
- Remove requirement to deselect target direction before selecting another
- Allow clicking functions/subnodes to toggle expansion instead of only expansion buttons
- Allow ItemID entry in relevant fields
- Indicate mode of entry fields more clearly (Slightly more red is hard to see)

**Comment by naab007** [comment]
Making it scroll through 1 machine at the time instead of 1 pixel at a time while selecting machines would also be nice.

**Comment by torterra2234** [comment]
a square grid, or some way of lining up commands and making the connections straight, because some people are ocd like that

**Comment by Vswe** [comment]
- ~~"Panning of work area, currently have to break up into multiple managers"~~ [handled with groups]
- ~~"Break all lists into vertical, scrollable rows instead of horizontal lists"~~ [done]
- ~~"Support mousewheel in lists"~~ [done]
- ~~"Remove requirement to deselect target direction before selecting another"~~ [done]
- ~~"Allow clicking functions/subnodes to toggle expansion instead of only expansion buttons"~~ [I don't agree on this one]
- ~~"Allow ItemID entry in relevant fields"~~ [no need, search for ".inv"]
- ~~"Indicate mode of entry fields more clearly (Slightly more red is hard to see)"~~ [done]

**Comment by Xuerian** [comment]
Awesome. Thanks :D
