### ISSUE TITLE
Block breaker/placer

### ISSUE THREAD

**Issue by Vswe** [Vswe/ModJam3#25]
Would, if added, be an inventory that had one item in its inventory, the block in front of it. By extracting the item from the inventory that block would be removed and by pumping on item into the inventory would place that block.

**Comment by ghost** [comment]
How would it handle ores? like silk touch or would you simulate a block breaking procedure?

**Comment by Vswe** [comment]
I would assume it would try to break it. Or does silk touch makes more sense?

**Comment by ghost** [comment]
Trying to break it makes more sense but it may cause some difficulties using whitelists when the block differs from what you actually get...

**Comment by DrSilix** [comment]
i think by the way you describe it's functions it would make more sense for silk touch, you get the block you are extracting. however when you add the element of gameplay into it silk touch is one of if not the rarest enchantment in the game and that effects the recipe greatly. so IMO if your comfortable with making a recipe for the block that reflects the rarity of silk touch then i think that would be best, but if you want the block to be accesible and cheap then no silk touch. however, again, instead of balance through the recipe an upgrade could be used to add silk touch, or i don't know if you plan on having a power requirement ever but thats another option to balance silk touch

**Comment by Vswe** [comment]
Would it really be OP to have a block with silk touch that you have to carry around? You would also have to carry around your manager and set its commands up again. I mean, silk touch enchantments are rare, but they are on tools that can be easily used.

**Comment by DrSilix** [comment]
It depends I think it would be fine in the early stages of SFM to have silk touch on the breaker. In a roughly vanilla environment yea silk touch no biggie, but some mods use the rarity of silk touch as a gate to more powerful mechanics, as an example rotarycraft allows duplication of any ore up to 6-15 results, one of the later game benefits to this is to silk touch ores which do not drop themselves so that they can take advantage of this feature such as diamonds or AE quartz. another example would be TE cinnabar i think it's called, it is only obtainable AFAIK from pulverized redstone ORE, this cinnabar allows great benefits including triple ore output and guaranteed alternate results. It's one of those mod interaction things, though i assume your not too worried about balance at this point.

 If you have an easily craftable silk touch block in a release version people most likely will call for a config option or nerf and then every modpack or server that balances will turn off the silk touch ... I think your best bet would be at least a plan to add an upgrade that allows the option of using silk touch, and maybe even allows the mining of obsidian or even diamond or tinker's cobalt.

**Comment by SomewhatDamaged** [comment]
Yeah, but it is hardly a scalable way to get the silk-touch effect. You need to find some redstone, place breaker, place cable, place manager, place chest, program manager, tear everything back up and find the next piece of redstone.

A simple way to make this so people cannot argue about it, make a book with the silk touch enchantment on it be a part of the crafting pattern to make it, as you did with efficiency and one of the Carts items.

**Comment by Vswe** [comment]
Added in alpha 41.
