### ISSUE TITLE
Odd issues with items being fetched unexpectedly

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#53]
I've been making rather eager use of Command Groups since their introduction. One of the techniques I've been experimenting with is using a command group to represent 5 sources of objects to connect to other command groups when needed.

The problem I'm experiencing is that when I connect the pin of one of the outputs of the source group to any non-whitelist output, either directly or indirectly (inside a group), objects will be fetched from ANY of the containers in the source group.

https://dl.dropboxusercontent.com/u/37472066/mc%20bits/2014-02-14_08.16.28.png
This shows the arrangement of the source group in question; each of the five sets corresponds to a single barrel.

https://dl.dropboxusercontent.com/u/37472066/mc%20bits/2014-02-14_08.17.03.png
This is the consumer of the materials in the first group.

No matter which one of the 5 pins from the first group I connect to any of the 5 pins of the second group, ALL of the barrels in the first group will end up passed to the second group.

This behavior is exhibited whether or not the input nodes in the first group are whitelist or blacklist.

Version is A60.

**Comment by Vswe** [comment]
How are these two pictures related and what is the desired result? Also, how is the split command configured?

**Comment by esotericist** [comment]
The two pictures are related in that I can connect any of the five output pins of the first group to any of the input pins of the second group and get the problematic behavior.

The desired result is whichever pin from the first group I connect to is the ONLY thing that feeds into the second group. The ACTUAL result is that ALL of input nodes in the first group are treated as inputs for the second group, instead of the input node associated with the connected pin.

The split command is sequential, but all it's sending is the event from the 1 second timer, so its configuration shouldn't really matter.

**Comment by Vswe** [comment]
Well, you use a split command. It will go through all of the output pins.

**Comment by esotericist** [comment]
That doesn't make any sense at all.

I have the trigger, which is a 1 second interval. The split is sending that to five 'input' nodes, each using a different barrel.

Each of those is connected to a different 'group node', for connectivity outside of the command group.

I connect ONE of those external pins to something else, which SHOULD only result in a single 'input' node having connectivity, so only one of the five barrels should be accessed.

SFM acted in these cases as if I had connected ALL of those pins, instead of only one.

This cannot possibly be intended behavior.

**Comment by Vswe** [comment]
Did you select the right-most pin?

**Comment by esotericist** [comment]
Between your last question and your earlier question about the split behavior, I was able to assemble some tests to get a clearer handle on the behavior. This prompts me to ask a question of you:

Why did you decide to have the split command in sequential mode establish a bi-directional relationship with command chains connected to its output pins, such that anything connected to one of those output pins is also essentially connected to everything on pins to the right of that pin on the split?

The paradigm you have established here implies a one-way relationship from input pin to output pin. This behavior violates the internal model you are encouraging users to build.

**Comment by Vswe** [comment]
The split command in sequential mode goes through the child chains one by one, in a sequence. Connections are one-way, but the inner state of the execution machine has nothing to do with the fact that they are. 

The commands in a program all operate on the execution machine's inner state, then you just define in what order this should happen. This is why multiple inputs can be connected to each other followed by a single output. You simply tell all the inputs to modify the inner state and then when the output is executed it uses (and modifies) this inner state.

The same behavior that you can see with a sequential split can be seen in a for each loop. Each time you go into the loop you just modify and use the inner state of the machine. Therefore, something you did for the previous element in the loop can effect the next one. The option would be to create new execution machine for each element in the loop. This would limit the program since you wouldn't be able to interact with anything outside of the current element's loop instance.

However, the split setting in the split command creates new execution machines which allow for multiple inner states at the same time.

**Comment by esotericist** [comment]
I disagree with the design choices you made here, but clearly there isn't a bug with this.

**Comment by Vswe** [comment]
What design choice would you have preferred then?
